import dotenv from 'dotenv';
import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { ZATCA_PACKAGE_ROOT } from './paths.js';

let envLoadState = /** @type {'never' | 'ok' | 'missing-file'} */ ('never');

/** Placeholder written when `ZATCA_OTP` is not set in `process.env` at auto-create time. */
export const ZATCA_OTP_PLACEHOLDER = 'SET_YOUR_OTP_HERE';

/**
 * Escape a value for a KEY=value line in .env (minimal safe quoting).
 * @param {string} value
 */
function formatEnvLine(key, value) {
  const v = String(value);
  if (v === '') {
    return `${key}=`;
  }
  if (!/[\s#"'=\\]/.test(v)) {
    return `${key}=${v}`;
  }
  const escaped = v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, '\\n');
  return `${key}="${escaped}"`;
}

/**
 * Default integration `.env` body — paths stay under integrations/zatca-einvoicing/.
 * CSR bootstrap file is committed for dry validation; replace with Laravel CSR path for production CSID.
 */
function buildAutoIntegrationDotenvContents(otpValue) {
  return `# Auto-generated by ZATCA Node integration — do not move outside integrations/zatca-einvoicing/
# Replace ZATCA_OTP before a real CSID request if it is still the placeholder.
${formatEnvLine('ZATCA_OTP', otpValue)}
ZATCA_COMPLIANCE_URL=https://sandbox.zatca.gov.sa/IntegrationSandbox
ZATCA_STORAGE_APP_ROOT=.
ZATCA_CSR_FILE_PATH=storage/zatca/bootstrap-for-validate.pem
ZATCA_CREDENTIALS_STORE_PATH=./storage/zatca/compliance-credentials.json
ZATCA_HTTP_TIMEOUT_MS=120000
`;
}

/**
 * Create integrations/zatca-einvoicing/.env only (never touches Laravel root .env).
 * @returns {boolean} true if file was created this call
 */
function ensureIntegrationDotenvFile() {
  const envPath = join(ZATCA_PACKAGE_ROOT, '.env');
  const localPath = join(ZATCA_PACKAGE_ROOT, '.env.local');

  if (existsSync(envPath)) {
    return false;
  }

  mkdirSync(join(ZATCA_PACKAGE_ROOT, 'storage', 'zatca'), { recursive: true });

  const otpFromProcess = process.env.ZATCA_OTP?.trim();
  const otpValue =
    otpFromProcess !== undefined && otpFromProcess !== '' ? otpFromProcess : ZATCA_OTP_PLACEHOLDER;

  const contents = buildAutoIntegrationDotenvContents(otpValue);
  writeFileSync(envPath, contents, { encoding: 'utf8', mode: 0o600 });
  try {
    chmodSync(envPath, 0o600);
  } catch {
    // Windows or FS may ignore mode; non-fatal
  }

  // eslint-disable-next-line no-console
  console.error('[ZATCA] .env file auto-created and loaded successfully');

  return true;
}

/**
 * Load ONLY `integrations/zatca-einvoicing/.env` (and optional `.env.local` after).
 * Auto-creates `.env` in this package if missing (never Laravel root).
 */
export function loadZatcaEnv() {
  const envPath = join(ZATCA_PACKAGE_ROOT, '.env');
  const localPath = join(ZATCA_PACKAGE_ROOT, '.env.local');

  const autoCreated = ensureIntegrationDotenvFile();

  let loadedAny = false;

  if (existsSync(envPath)) {
    dotenv.config({ path: envPath, override: true });
    loadedAny = true;
  }

  if (existsSync(localPath)) {
    dotenv.config({ path: localPath, override: true });
    loadedAny = true;
  }

  envLoadState = loadedAny ? 'ok' : 'missing-file';

  return {
    packageRoot: ZATCA_PACKAGE_ROOT,
    envPath,
    envExists: existsSync(envPath),
    localExists: existsSync(localPath),
    loadedAny,
    autoCreated,
  };
}

/**
 * Idempotent: safe to call from CLI, `buildZatcaConfig`, and `requestComplianceCsid`.
 */
export function ensureZatcaEnvLoaded() {
  if (envLoadState === 'never') {
    loadZatcaEnv();
  }
}

/** @internal */
export function resetZatcaEnvLoadStateForTests() {
  envLoadState = 'never';
}

export function getZatcaEnvLoadState() {
  return envLoadState;
}

export function getExpectedZatcaEnvPath() {
  return join(ZATCA_PACKAGE_ROOT, '.env');
}

export function buildZatcaConfig() {
  ensureZatcaEnvLoaded();

  const pkgRoot = ZATCA_PACKAGE_ROOT;

  const complianceUrl =
    process.env.ZATCA_COMPLIANCE_URL?.trim() ||
    'https://sandbox.zatca.gov.sa/IntegrationSandbox';

  const otp = process.env.ZATCA_OTP?.trim() ?? '';
  const timeoutMs = Math.max(5_000, parseInt(process.env.ZATCA_HTTP_TIMEOUT_MS ?? '120000', 10) || 120_000);

  const storageAppRoot = resolve(pkgRoot, process.env.ZATCA_STORAGE_APP_ROOT?.trim() || '../../storage/app');

  const csrFilePath = process.env.ZATCA_CSR_FILE_PATH?.trim() || '';
  const csrPemEnv = process.env.ZATCA_CSR_PEM?.trim() || '';
  const useDatabaseCsr = ['1', 'true', 'yes'].includes(
    (process.env.ZATCA_USE_DATABASE_CSR ?? '').toLowerCase(),
  );

  const credentialsStorePath = resolve(
    pkgRoot,
    process.env.ZATCA_CREDENTIALS_STORE_PATH?.trim() || './storage/zatca/compliance-credentials.json',
  );

  const databaseUrl = process.env.ZATCA_DATABASE_URL?.trim() || process.env.DATABASE_URL?.trim() || '';

  return {
    complianceUrl,
    otp,
    timeoutMs,
    storageAppRoot,
    csrFilePath,
    csrPemEnv,
    useDatabaseCsr,
    databaseUrl,
    credentialsStorePath,
    packageRoot: pkgRoot,
    expectedEnvFile: getExpectedZatcaEnvPath(),
    envFilePresent: existsSync(getExpectedZatcaEnvPath()),
    otpIsPlaceholder: otp === ZATCA_OTP_PLACEHOLDER,
  };
}

/**
 * OTP must come from environment (populated via this package `.env` / `.env.local` or CI exports).
 * @param {ReturnType<typeof buildZatcaConfig>} cfg
 */
export function assertComplianceRequestConfig(cfg) {
  const envHint = cfg.envFilePresent
    ? `integrations/zatca-einvoicing/.env (${cfg.expectedEnvFile})`
    : `no file at ${cfg.expectedEnvFile} — use that path or export ZATCA_OTP in the process environment`;

  if (!cfg.otp) {
    throw new Error(
      [
        'ZATCA_OTP is missing or empty.',
        'It must be set only via environment variables (typically in the integration .env file).',
        `Expected env file: ${cfg.expectedEnvFile}`,
        cfg.envFilePresent
          ? 'The file exists — add a line: ZATCA_OTP=your_otp_from_fatoora_portal'
          : 'Create the file: copy integrations/zatca-einvoicing/.env.example to .env and set ZATCA_OTP.',
        `Resolved context: ${envHint}`,
      ].join(' '),
    );
  }

  if (!cfg.csrPemEnv && !cfg.csrFilePath && !cfg.useDatabaseCsr) {
    throw new Error(
      'CSR source not configured: set ZATCA_CSR_PEM, or ZATCA_CSR_FILE_PATH (+ ZATCA_STORAGE_APP_ROOT), or ZATCA_USE_DATABASE_CSR=true with DATABASE_URL.',
    );
  }
  if (cfg.useDatabaseCsr && !cfg.databaseUrl) {
    throw new Error('ZATCA_USE_DATABASE_CSR requires ZATCA_DATABASE_URL or DATABASE_URL.');
  }
}

/**
 * Dry validation (no HTTP): OTP + CSR config. Used by validate CLI.
 * @returns {Promise<{ ok: boolean, packageRoot: string, otpSet: boolean, otpPlaceholder: boolean, csrSource: string }>}
 */
export async function runComplianceDryValidation(resolveCsrPemFn) {
  const cfg = buildZatcaConfig();
  assertComplianceRequestConfig(cfg);
  const { source } = await resolveCsrPemFn(cfg);
  return {
    ok: true,
    packageRoot: cfg.packageRoot,
    otpSet: Boolean(cfg.otp?.trim()),
    otpPlaceholder: Boolean(cfg.otpIsPlaceholder),
    csrSource: source,
  };
}
