<?php

declare(strict_types=1);

/**
 * ERP module sidebar links and surfaces (PR-4).
 * Merged into config/navigation.php at load time.
 */
return [

    'links' => [

        // —— Sales ——
        'sales.customers' => [
            'route' => 'sales.customers.index',
            'label' => 'العملاء',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.customers.*',
        ],
        'sales.quotations' => [
            'route' => 'sales.quotations.index',
            'label' => 'عروض الأسعار',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.quotations.*',
        ],
        'sales.orders' => [
            'route' => 'sales.orders.index',
            'label' => 'أوامر البيع',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => ['sales.orders.index', 'sales.orders.create', 'sales.orders.store', 'sales.orders.show'],
        ],
        'sales.delivery_orders' => [
            'route' => 'sales.delivery-orders.index',
            'label' => 'أوامر التوريد',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => ['sales.delivery-orders.*', 'sales.orders.delivery-orders.*'],
        ],
        'sales.invoices' => [
            'route' => 'sales.invoices.index',
            'label' => 'الفواتير',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.invoices.*',
        ],
        'sales.payments' => [
            'route' => 'sales.payments.index',
            'label' => 'المدفوعات',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.payments.*',
        ],
        'sales.returns' => [
            'route' => 'sales.returns.index',
            'label' => 'مرتجعات المبيعات',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.returns.*',
        ],
        'sales.installments' => [
            'route' => 'sales.installments.index',
            'label' => 'الأقساط',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.installments.*',
        ],
        'sales.targets' => [
            'route' => 'sales.targets.index',
            'label' => 'أهداف المبيعات',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.targets.*',
        ],
        'sales.commissions' => [
            'route' => 'sales.commissions.index',
            'label' => 'العمولات',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.commissions.*',
        ],
        'sales.contracts' => [
            'route' => 'sales.contracts.index',
            'label' => 'العقود',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.contracts.*',
        ],
        'sales.einvoice' => [
            'route' => 'sales.einvoice.settings.edit',
            'label' => 'الفوترة الإلكترونية',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.einvoice.*',
        ],
        'sales.reports.statement' => [
            'route' => 'reports.statement.index',
            'label' => 'كشف حساب العميل',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'reports.statement.*',
        ],

        // —— Purchases ——
        'purchases.suppliers' => [
            'route' => 'purchases.suppliers.index',
            'label' => 'الموردين',
            'shell' => 'purchases',
            'module' => 'purchases',
            'active' => 'purchases.suppliers.*',
        ],
        'purchases.orders' => [
            'route' => 'purchases.orders.index',
            'label' => 'أوامر الشراء',
            'shell' => 'purchases',
            'module' => 'purchases',
            'active' => 'purchases.orders.*',
        ],
        'purchases.receive_notes' => [
            'route' => 'purchases.receive-notes.index',
            'label' => 'سندات الاستلام',
            'shell' => 'purchases',
            'module' => 'purchases',
            'active' => 'purchases.receive-notes.*',
        ],
        'purchases.invoices' => [
            'route' => 'purchases.invoices.index',
            'label' => 'فواتير الموردين',
            'shell' => 'purchases',
            'module' => 'purchases',
            'active' => 'purchases.invoices.*',
        ],
        'purchases.payments' => [
            'route' => 'purchases.payments.index',
            'label' => 'مدفوعات الموردين',
            'shell' => 'purchases',
            'module' => 'purchases',
            'active' => 'purchases.payments.*',
        ],
        'purchases.returns' => [
            'route' => 'purchases.returns.index',
            'label' => 'مرتجعات المشتريات',
            'shell' => 'purchases',
            'module' => 'purchases',
            'active' => 'purchases.returns.*',
        ],
        'purchases.reports' => [
            'route' => 'purchases.reports.index',
            'label' => 'تقارير المشتريات',
            'shell' => 'purchases',
            'module' => 'purchases',
            'active' => 'purchases.reports.*',
        ],

        // —— Inventory ——
        'inventory.items' => [
            'route' => 'items.index',
            'label' => 'المنتجات',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'items.*',
        ],
        'inventory.warehouses' => [
            'route' => 'warehouses.index',
            'label' => 'المستودعات',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'warehouses.*',
        ],
        'inventory.transfers' => [
            'route' => 'inventory.transfers.index',
            'label' => 'تحويلات المخزون',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'inventory.transfers.*',
        ],
        'inventory.adjustments' => [
            'route' => 'inventory.adjustments.index',
            'label' => 'تسويات المخزون',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'inventory.adjustments.*',
        ],
        'inventory.audits' => [
            'route' => 'inventory.audits.index',
            'label' => 'جرد المخزون',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'inventory.audits.*',
        ],
        'inventory.movements' => [
            'route' => 'inventory.movements.index',
            'label' => 'حركات المخزون',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'inventory.movements.*',
        ],
        'inventory.price_lists' => [
            'route' => 'inventory.price-lists.index',
            'label' => 'قوائم الأسعار',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'inventory.price-lists.*',
        ],
        'inventory.reports.valuation' => [
            'route' => 'inventory.reports.valuation',
            'label' => 'تقييم المخزون',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'inventory.reports.valuation',
        ],

        // —— Manufacturing ——
        'manufacturing.items' => [
            'route' => 'items.index',
            'label' => 'الأصناف',
            'shell' => 'manufacturing',
            'module' => 'manufacturing',
            'active' => 'items.*',
        ],
        'manufacturing.bom_lists' => [
            'route' => 'manufacturing.bom-lists.index',
            'label' => 'قوائم المواد',
            'shell' => 'manufacturing',
            'module' => 'manufacturing',
            'active' => 'manufacturing.bom-lists.*',
        ],
        'manufacturing.runs' => [
            'route' => 'manufacturing.runs.index',
            'label' => 'أوامر العمل',
            'shell' => 'manufacturing',
            'module' => 'manufacturing',
            'active' => [
                'manufacturing.runs.index',
                'manufacturing.create',
                'manufacturing.show',
                'manufacturing.store',
                'manufacturing.post',
                'manufacturing.destroy',
            ],
        ],
        'manufacturing.reports.production_variance' => [
            'route' => 'manufacturing.reports.production-variance',
            'label' => 'انحرافات التصنيع',
            'shell' => 'manufacturing',
            'module' => 'manufacturing',
            'active' => 'manufacturing.reports.production-variance',
        ],

        // —— Finance (extended) ——
        'finance.expenses.categories' => [
            'route' => 'finance.expenses.categories.index',
            'label' => 'تصنيفات المصروفات',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.expenses.categories.*',
        ],
        'finance.fixed_assets' => [
            'route' => 'finance.fixed-assets.index',
            'label' => 'الأصول الثابتة',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.fixed-assets.*',
        ],
        'finance.cost_centers' => [
            'route' => 'finance.cost-centers.index',
            'label' => 'مراكز التكلفة',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.cost-centers.*',
        ],
        'finance.cheques' => [
            'route' => 'finance.cheques.index',
            'label' => 'الشيكات',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.cheques.*',
        ],
        'finance.bank_accounts' => [
            'route' => 'finance.bank-accounts.index',
            'label' => 'الحسابات البنكية',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.bank-accounts.*',
        ],
        'finance.bank_reconciliations' => [
            'route' => 'finance.bank-reconciliations.index',
            'label' => 'تسوية البنك',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.bank-reconciliations.*',
        ],
        'finance.credit_notes' => [
            'route' => 'finance.credit-notes.index',
            'label' => 'إشعارات الائتمان',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.credit-notes.*',
        ],
        'finance.debit_notes' => [
            'route' => 'finance.debit-notes.index',
            'label' => 'إشعارات المديونية',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.debit-notes.*',
        ],
        'finance.budgets' => [
            'route' => 'finance.budgets.index',
            'label' => 'الموازنات',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.budgets.*',
        ],
        'finance.reports.trial_balance' => [
            'route' => 'finance.reports.trial-balance',
            'label' => 'التقارير المالية - ميزان المراجعة',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.reports.trial-balance',
        ],
        'finance.reports.ar_aging' => [
            'route' => 'finance.reports.ar-aging',
            'label' => 'أعمار الذمم المدينة',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.reports.ar-aging',
        ],
        'finance.reports.ap_aging' => [
            'route' => 'finance.reports.ap-aging',
            'label' => 'أعمار الذمم الدائنة',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.reports.ap-aging',
        ],

        // —— HR ——
        'hr.shifts' => [
            'route' => 'hr.shifts.index',
            'label' => 'الورديات',
            'shell' => 'hr',
            'module' => 'hr',
            'active' => 'hr.shifts.*',
        ],
        'hr.departments' => [
            'route' => 'hr.departments.index',
            'label' => 'الأقسام',
            'shell' => 'hr',
            'module' => 'hr',
            'active' => 'hr.departments.*',
        ],
        'hr.employees' => [
            'route' => 'hr.employees.index',
            'label' => 'الموظفون',
            'shell' => 'hr',
            'module' => 'hr',
            'active' => 'hr.employees.*',
        ],
        'hr.attendance' => [
            'route' => 'hr.attendance',
            'label' => 'الحضور',
            'shell' => 'hr',
            'module' => 'hr',
            'active' => 'hr.attendance',
        ],
        'hr.payrolls' => [
            'route' => 'hr.payrolls.index',
            'label' => 'الرواتب',
            'shell' => 'hr',
            'module' => 'hr',
            'active' => ['hr.payrolls.*', 'hr.payroll-slips.*'],
            'permission' => 'manage_payroll',
        ],
        'hr.leave_requests' => [
            'route' => 'hr.leave-requests',
            'label' => 'طلبات الإجازة',
            'shell' => 'hr',
            'module' => 'hr',
            'active' => ['hr.leave-requests', 'hr.leave-requests.create'],
        ],
        'hr.overtime' => [
            'route' => 'hr.overtime',
            'label' => 'الوقت الإضافي',
            'shell' => 'hr',
            'module' => 'hr',
            'active' => 'hr.overtime*',
            'permission' => 'manage_payroll',
        ],

        // —— Services ——
        'services.technician' => [
            'route' => 'services.technician.index',
            'label' => 'مهام الفني',
            'shell' => 'services',
            'module' => 'services',
            'active' => 'services.technician.*',
            'technician_or_admin' => true,
        ],
        'services.dashboard' => [
            'route' => 'services.dashboard',
            'label' => 'لوحة الخدمات',
            'shell' => 'services',
            'module' => 'services',
            'active' => 'services.dashboard',
            'admin_only' => true,
        ],
        'services.orders' => [
            'route' => 'services.orders.index',
            'label' => 'طلبات الخدمة',
            'shell' => 'services',
            'module' => 'services',
            'active' => [
                'services.orders.index',
                'services.orders.show',
                'services.orders.store',
                'services.orders.assign',
                'services.orders.parts.store',
                'services.orders.complete',
                'services.orders.cancel',
            ],
            'admin_only' => true,
        ],
        'services.orders_create' => [
            'route' => 'services.orders.create',
            'label' => 'طلب جديد',
            'shell' => 'services',
            'module' => 'services',
            'active' => 'services.orders.create',
            'admin_only' => true,
        ],
    ],

    'surfaces' => [
        'sales.full' => [
            'sales.dashboard',
            'sales.customers',
            'sales.quotations',
            'sales.orders',
            'sales.delivery_orders',
            'sales.invoices',
            'sales.payments',
            'sales.returns',
            'sales.installments',
            'sales.targets',
            'sales.commissions',
            'sales.contracts',
            'sales.einvoice',
            'sales.reports.statement',
        ],
        'sales.lite' => [
            'sales.dashboard',
            'sales.customers',
            'sales.invoices',
            'sales.payments',
        ],
        'purchases.full' => [
            'purchases.dashboard',
            'purchases.suppliers',
            'purchases.orders',
            'purchases.receive_notes',
            'purchases.invoices',
            'purchases.payments',
            'purchases.returns',
            'purchases.reports',
        ],
        'purchases.lite' => [
            'purchases.dashboard',
            'purchases.suppliers',
            'purchases.orders',
        ],
        'inventory.full' => [
            'inventory.dashboard',
            'inventory.items',
            'inventory.warehouses',
            'inventory.transfers',
            'inventory.adjustments',
            'inventory.audits',
            'inventory.movements',
            'inventory.price_lists',
            'inventory.reports.valuation',
        ],
        'inventory.lite' => [
            'inventory.dashboard',
            'inventory.items',
            'inventory.warehouses',
        ],
        'manufacturing.full' => [
            'manufacturing.dashboard',
            'manufacturing.items',
            'manufacturing.bom_lists',
            'manufacturing.runs',
            'manufacturing.reports.production_variance',
        ],
        'finance.full' => [
            'finance.dashboard',
            'finance.accounts',
            'finance.journals',
            'finance.expenses',
            'finance.expenses.categories',
            'finance.fixed_assets',
            'finance.cost_centers',
            'finance.cheques',
            'finance.bank_accounts',
            'finance.bank_reconciliations',
            'finance.credit_notes',
            'finance.debit_notes',
            'finance.budgets',
            'finance.reports.trial_balance',
            'finance.reports.ar_aging',
            'finance.reports.ap_aging',
            'finance.reports.profit_loss',
        ],
        'hr.full' => [
            'hr.dashboard',
            'hr.shifts',
            'hr.departments',
            'hr.employees',
            'hr.attendance',
            'hr.payrolls',
            'hr.leave_requests',
            'hr.overtime',
        ],
        'hr.lite' => [
            'hr.dashboard',
            'hr.employees',
            'hr.attendance',
        ],
        'services.full' => [
            'services.technician',
            'services.dashboard',
            'services.orders',
            'services.orders_create',
        ],
    ],

    'module_shells' => [
        'sales' => [
            'title' => 'المبيعات',
            'iconBg' => 'rgba(46, 125, 50, 0.2)',
            'iconColor' => '#2e7d32',
            'icon' => '<path d="M4 11H2v3h2v-3zm5-4H7v7h2V7zm5-5v12h-2V2h2zm-2-1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1h-2z"/>',
        ],
        'purchases' => [
            'title' => 'المشتريات',
            'iconBg' => 'rgba(124, 58, 237, 0.2)',
            'iconColor' => '#7c3aed',
            'icon' => '<path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5z"/>',
        ],
        'inventory' => [
            'title' => 'المخزون',
            'iconBg' => 'rgba(245, 158, 11, 0.25)',
            'iconColor' => '#ea580c',
            'icon' => '<path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113z"/><path d="M15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6z"/>',
        ],
        'manufacturing' => [
            'title' => 'التصنيع',
            'iconBg' => 'rgba(59, 130, 246, 0.18)',
            'iconColor' => '#1d4ed8',
            'icon' => '<path d="M8 1a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V1zm1 0v14h6V1H9zM2 3a1 1 0 0 1 1-1h3v14H3a1 1 0 0 1-1-1V3z"/>',
        ],
        'finance' => [
            'title' => 'المحاسبة المالية',
            'iconBg' => 'rgba(2, 119, 189, 0.2)',
            'iconColor' => '#0277bd',
            'icon' => '<path d="M4 10.781c.148 1.667 1.513 2.85 3.591 3.003V15h1.043v-1.216c2.27-.179 3.678-1.438 3.678-3.3 0-1.59-.947-2.51-2.956-3.028l-.722-.187V3.467c1.122.11 1.879.714 2.07 1.616h1.471c-.166-1.6-1.54-2.748-3.54-2.875V1H7.591v1.233c-1.939.23-3.27 1.472-3.27 3.156 0 1.454.966 2.483 2.661 2.917l.61.162v4.031c-1.149-.17-1.94-.8-2.131-1.718H4z"/>',
        ],
        'services' => [
            'title' => 'الخدمات والصيانة',
            'iconBg' => 'rgba(14, 165, 233, 0.18)',
            'iconColor' => '#0284c7',
            'icon' => '<path d="M8.5 1.5a.5.5 0 0 0-1 0v1.086c-.563.097-1.159.236-1.668.43C5.48 3.328 5 4.108 5 5c0 .653.183 1.254.528 1.755.345.502.86.93 1.52 1.263.66.332 1.453.58 2.328.744V13H8v-1h1v-1.08c.563-.098 1.159-.237 1.668-.431 1.354-.312 2.332-1.092 2.332-1.991 0-.653-.183-1.254-.528-1.755-.345-.502-.86-.93-1.52-1.263C9.792 5.18 8.999 4.932 8.124 4.768V3h.5v1H8V3h-.5v1H7V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5V3z"/><path d="M6.5 14.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>',
        ],
        'hr' => [
            'title' => 'الموارد البشرية',
            'iconBg' => 'rgba(13, 148, 136, 0.18)',
            'iconColor' => '#0d9488',
            'icon' => '<path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/><path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>',
        ],
    ],

];
