<?php

declare(strict_types=1);

/**
 * Akwad SaaS — القاموس الافتراضي + مسميات كل نيش.
 * المفتاح: dot notation (modules.inventory، entities.customer، …).
 * تُدمَج overrides النيش فوق defaults عند التحميل.
 */
return [

    'defaults' => [
        'modules.finance' => 'المحاسبة',
        'modules.inventory' => 'المخزون',
        'modules.warehouses' => 'المستودعات',
        'modules.items' => 'الأصناف',
        'modules.manufacturing' => 'التصنيع',
        'modules.sales' => 'المبيعات',
        'modules.purchases' => 'المشتريات',
        'modules.hr' => 'الموارد البشرية',
        'modules.pos' => 'نقاط البيع',
        'modules.crm' => 'إدارة العملاء',
        'modules.services' => 'الخدمات والصيانة',
        'modules.clinic' => 'العيادة',
        'modules.nursery' => 'الحضانة',
        'modules.fleet' => 'المناديب',
        'modules.restaurant' => 'المطعم',
        'entities.customer' => 'العميل',
        'entities.supplier' => 'المورد',
        'entities.item' => 'الصنف',
        'entities.warehouse' => 'المستودع',
        'entities.invoice' => 'الفاتورة',
        'entities.employee' => 'الموظف',
        'finance.dashboard' => 'لوحة المحاسبة',
        'finance.summary' => 'ملخص المالية',
        'finance.revenue' => 'الإيرادات',
        'finance.collections' => 'التحصيلات',
        'finance.receivable' => 'الذمم المدينة',
        'finance.expense' => 'المصروفات',
        'finance.expense_categories' => 'تصنيفات المصروفات',
        'finance.receipt' => 'سند قبض',
        'finance.payment' => 'سند صرف',
        'finance.cash' => 'النقدية',
        'finance.accounts' => 'دليل الحسابات',
        'finance.journals' => 'القيود اليومية',
        'finance.ledger' => 'دفتر الأستاذ',
        'finance.trial_balance' => 'ميزان المراجعة',
        'finance.profit_loss' => 'الأرباح والخسائر',
        'finance.tax_report' => 'التقرير الضريبي',
        'finance.tax_rates' => 'معدلات الضريبة',
        'finance.bank_accounts' => 'الحسابات البنكية',
        'finance.bank_reconciliation' => 'التسوية البنكية',
        'finance.payment_method_accounts' => 'ربط طرق الدفع',
    ],

    'niche_overrides' => [

        'manufacturing' => [
            'modules.inventory' => 'مخزن الخامات',
            'modules.warehouses' => 'مخازن الخامات',
            'modules.items' => 'المواد والمنتجات',
            'modules.manufacturing' => 'خط الإنتاج',
            'modules.purchases' => 'توريد الخامات',
            'modules.sales' => 'مبيعات المصنع',
            'modules.pos' => 'كاشير المعرض',
            'entities.customer' => 'عميل التوزيع',
            'entities.supplier' => 'مورد الخامات',
            'entities.warehouse' => 'مخزن خامات',
            'entities.item' => 'مادة / منتج',
        ],

        'retail' => [
            'modules.inventory' => 'المعرض والمستودع',
            'modules.warehouses' => 'المعارض والمستودعات',
            'modules.items' => 'المنتجات المعروضة',
            'modules.sales' => 'مبيعات المتجر',
            'modules.crm' => 'عملاء المتجر',
            'modules.pos' => 'كاشير المتجر',
            'entities.customer' => 'عميل المتجر',
            'entities.warehouse' => 'المعرض / المستودع',
            'entities.item' => 'منتج',
        ],

        'medical_clinics' => [
            'modules.clinic' => 'العيادة',
            'modules.crm' => 'ملفات المرضى',
            'modules.services' => 'الروشتات والخدمات',
            'modules.hr' => 'طاقم العيادة',
            'modules.pos' => 'كاشير المستلزمات',
            'entities.customer' => 'المريض',
            'entities.invoice' => 'فاتورة الكشف',
            'entities.employee' => 'طبيب / موظف',
        ],

        'nurseries' => [
            'modules.nursery' => 'الحضانة',
            'modules.hr' => 'معلمات الحضانة',
            'modules.finance' => 'مالية الحضانة',
            'modules.pos' => 'متجر الحضانة',
            'entities.customer' => 'ولي الأمر',
            'entities.invoice' => 'فاتورة الاشتراك',
            'entities.employee' => 'معلمة / موظف',
            'entities.child' => 'طفل',
            'entities.classroom' => 'فصل',
            'finance.dashboard' => 'لوحة المالية',
            'finance.summary' => 'ملخص المالية',
            'finance.revenue' => 'إيرادات الحضانة',
            'finance.collections' => 'تحصيلات الاشتراكات',
            'finance.receivable' => 'مستحقات أولياء الأمور',
            'finance.expense' => 'مصروفات الحضانة',
            'finance.expense_categories' => 'تصنيفات المصروفات',
            'finance.receipt' => 'سند تحصيل',
            'finance.payment' => 'سند صرف',
            'finance.cash' => 'الخزينة',
            'finance.accounts' => 'دليل الحسابات',
            'finance.journals' => 'القيود اليومية',
            'finance.ledger' => 'دفتر الأستاذ',
            'finance.trial_balance' => 'ميزان المراجعة',
            'finance.profit_loss' => 'الأرباح والخسائر',
            'finance.tax_report' => 'تقرير الضريبة',
            'finance.tax_rates' => 'معدلات الضريبة',
            'finance.bank_accounts' => 'البنوك',
            'finance.bank_reconciliation' => 'التسوية البنكية',
            'finance.payment_method_accounts' => 'ربط طرق الدفع',
        ],

        'restaurants' => [
            'modules.finance' => 'المحاسبة',
            'modules.inventory' => 'المطبخ / المستودع',
            'modules.warehouses' => 'مخازن المطبخ',
            'modules.items' => 'قائمة الطعام / المكونات',
            'modules.purchases' => 'توريد المكونات',
            'modules.pos' => 'كاشير الصالة',
            'modules.hr' => 'طاقم الصالة والمطبخ',
            'modules.restaurant' => 'إدارة المطعم',
            'entities.customer' => 'الزبون',
            'entities.waiter' => 'الويتر',
            'entities.table' => 'طاولة',
            'entities.menu' => 'قائمة الطعام',
            'entities.order' => 'طلب المطبخ',
            'entities.item' => 'صنف القائمة',
            'entities.warehouse' => 'المطبخ / المستودع',
            'entities.invoice' => 'فاتورة الطلب',
            'entities.employee' => 'موظف الصالة / المطبخ',
        ],

        'fleet_agents' => [
            'modules.fleet' => 'العمليات الميدانية',
            'modules.inventory' => 'العهدة',
            'modules.warehouses' => 'مخازن العهدة',
            'modules.sales' => 'التحصيل الميداني',
            'modules.crm' => 'المناديب والعملاء',
            'modules.pos' => 'كاشير المندوب',
            'entities.customer' => 'عميل المندوب',
            'entities.agent' => 'المندوب',
            'entities.warehouse' => 'عهدة',
            'entities.item' => 'بضاعة العهدة',
            'entities.invoice' => 'إيصال تحصيل',
        ],

        'full_erp' => [
            'modules.finance' => 'المالية',
            'modules.inventory' => 'المخزون',
            'modules.sales' => 'المبيعات',
            'modules.purchases' => 'المشتريات',
            'modules.manufacturing' => 'التصنيع',
            'modules.hr' => 'الموارد البشرية',
            'modules.crm' => 'إدارة العملاء',
            'modules.pos' => 'نقاط البيع',
            'modules.clinic' => 'العيادة',
            'modules.services' => 'الخدمات',
        ],

    ],

];
