<?php

declare(strict_types=1);

use App\Support\ClinicAccess;
use App\Support\FleetAccess;
use App\Support\NurseryAccess;
use App\Support\StoreFeatureKeys;

/**
 * Navigation Profiles — فصل Module ON (backend) عن Nav Surface (UI).
 *
 * links:     تعريف كل رابط مرة واحدة
 * surfaces:  قائمة صريحة بمفاتيح الروابط (link-level filtering داخل الموديول)
 * profiles:  أي surfaces يعرضها كل niche
 * launchers: بطاقات الوصول السريع في erp-global-navbar (مرحلة N2)
 */
$erpNavigation = require __DIR__.'/erp_navigation.php';

$config = [

    'links' => [

        // —— POS ——
        'pos.dashboard' => [
            'route' => 'pos.dashboard',
            'label' => 'لوحة نقاط البيع',
            'shell' => 'pos',
            'module' => 'pos',
            'active' => 'pos.dashboard',
            'hint' => 'مبيعات اليوم والأجهزة',
        ],
        'pos.products' => [
            'route' => 'pos.products.index',
            'label' => 'المنتجات',
            'shell' => 'pos',
            'module' => 'pos',
            'active' => 'pos.products.*',
        ],
        'pos.store_settings' => [
            'route' => 'settings.store.edit',
            'label' => 'إعدادات المتجر',
            'store_label' => 'settings',
            'shell' => 'pos',
            'module' => 'pos',
            'active' => 'settings.store.*',
            'feature' => StoreFeatureKeys::ONLINE_STORE,
            'hint' => 'طرق الدفع والمتجر',
        ],
        'pos.cashier' => [
            'route' => 'pos.cashier',
            'label' => 'الكاشير',
            'shell' => 'pos',
            'module' => 'pos',
            'active' => 'pos.cashier',
        ],
        'pos.devices' => [
            'route' => 'pos.devices.index',
            'label' => 'الأجهزة',
            'shell' => 'pos',
            'module' => 'pos',
            'active' => 'pos.devices.*',
            'admin_only' => true,
        ],
        'pos.sessions' => [
            'route' => 'pos.sessions.index',
            'label' => 'الجلسات',
            'shell' => 'pos',
            'module' => 'pos',
            'active' => 'pos.sessions.*',
        ],
        'pos.orders' => [
            'route' => 'pos.orders.index',
            'label' => 'طلبات أونلاين',
            'store_label' => 'orders',
            'shell' => 'pos',
            'module' => 'pos',
            'active' => ['pos.orders.*', 'pos.online-orders.*'],
            'feature' => StoreFeatureKeys::ONLINE_STORE,
            'hint' => 'طلبات أونلاين',
        ],
        'pos.receipts' => [
            'route' => 'pos.receipts.index',
            'label' => 'الإيصالات',
            'shell' => 'pos',
            'module' => 'pos',
            'active' => 'pos.receipts.*',
        ],

        // —— Fleet ——
        'fleet.dashboard' => [
            'route' => 'fleet.dashboard',
            'label' => 'لوحة التحكم',
            'info_field' => 'fleet.nav_dashboard',
            'shell' => 'fleet',
            'module' => 'fleet',
            'active' => 'fleet.dashboard',
            'requires_fleet_operations' => true,
            'fleet_capability' => FleetAccess::CAP_VIEW_DASHBOARD,
            'hint' => 'مناديب وعملاء ميدان',
        ],
        'fleet.collections' => [
            'route' => 'fleet.collections.index',
            'label' => 'التحصيل الميداني',
            'info_field' => 'fleet.nav_collections',
            'shell' => 'fleet',
            'module' => 'fleet',
            'active' => 'fleet.collections.*',
            'requires_fleet_operations' => true,
            'fleet_capability' => FleetAccess::CAP_VIEW_COLLECTIONS,
        ],
        'fleet.custody' => [
            'route' => 'fleet.custody.index',
            'label' => 'العهدة',
            'niche_label' => 'modules.inventory',
            'info_field' => 'fleet.nav_custody',
            'shell' => 'fleet',
            'module' => 'fleet',
            'active' => 'fleet.custody.*',
            'requires_fleet_operations' => true,
            'fleet_capability' => FleetAccess::CAP_VIEW_CUSTODY,
        ],
        'fleet.store_orders' => [
            'route' => 'fleet.store-orders.index',
            'label' => 'طلبات المتجر',
            'info_field' => 'fleet.nav_store_orders',
            'shell' => 'fleet',
            'module' => 'fleet',
            'active' => 'fleet.store-orders.*',
            'requires_fleet_operations' => true,
            'fleet_capability' => FleetAccess::CAP_VIEW_STORE_ORDERS,
        ],
        'fleet.routes' => [
            'route' => 'fleet.routes.index',
            'label' => 'خطوط السير',
            'info_field' => 'fleet.nav_routes',
            'shell' => 'fleet',
            'module' => 'fleet',
            'active' => 'fleet.routes.*',
            'requires_fleet_operations' => true,
            'fleet_capability' => FleetAccess::CAP_VIEW_ROUTES,
        ],
        'fleet.agents' => [
            'route' => 'fleet.agents.index',
            'label' => 'المناديب',
            'niche_label' => 'entities.agent',
            'info_field' => 'fleet.nav_agents',
            'shell' => 'fleet',
            'module' => 'fleet',
            'active' => 'fleet.agents.*',
            'requires_fleet_operations' => true,
            'fleet_capability' => FleetAccess::CAP_MANAGE_AGENTS,
        ],
        'fleet.customers' => [
            'route' => 'fleet.customers.index',
            'label' => 'العملاء',
            'niche_label' => 'entities.customer',
            'info_field' => 'fleet.nav_customers',
            'shell' => 'fleet',
            'module' => 'fleet',
            'active' => 'fleet.customers.*',
            'requires_fleet_operations' => true,
            'fleet_capability' => FleetAccess::CAP_MANAGE_CUSTOMERS,
        ],
        'fleet.products' => [
            'route' => 'fleet.products.index',
            'label' => 'الكتalog الخفيف',
            'info_field' => 'fleet.nav_products',
            'shell' => 'fleet',
            'module' => 'fleet',
            'active' => 'fleet.products.*',
            'requires_fleet_operations' => true,
            'fleet_capability' => FleetAccess::CAP_MANAGE_PRODUCTS,
        ],

        // —— Finance ——
        'finance.dashboard' => [
            'route' => 'finance.dashboard',
            'label' => 'لوحة المحاسبة',
            'dashboard_label' => 'لوحة',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.dashboard',
            'hint' => 'مالية',
        ],
        'finance.reports.profit_loss' => [
            'route' => 'finance.reports.profit-loss',
            'label' => 'أرباح وخسائر',
            'dashboard_label' => 'أرباح',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.reports.profit-loss',
            'hint' => 'تقرير مالي',
        ],
        'finance.accounts' => [
            'route' => 'finance.accounts.index',
            'label' => 'دليل الحسابات',
            'dashboard_label' => 'دليل',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.accounts.*',
        ],
        'finance.journals' => [
            'route' => 'finance.journals.index',
            'label' => 'القيود',
            'dashboard_label' => 'قيود',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.journals.*',
        ],
        'finance.expenses' => [
            'route' => 'finance.expenses.index',
            'label' => 'المصروفات',
            'dashboard_label' => 'مصروفات',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.expenses.*',
        ],
        'finance.expenses.create' => [
            'route' => 'finance.expenses.create',
            'label' => 'إضافة مصروف',
            'dashboard_label' => 'إضافة مصروف',
            'dashboard_icon' => 'plus',
            'shell' => 'finance',
            'module' => 'finance',
            'active' => 'finance.expenses.create',
        ],

        // —— Clinic ——
        'clinic.dashboard' => [
            'route' => 'clinic.dashboard',
            'label' => 'لوحة العيادة',
            'info_field' => 'clinic.nav_dashboard',
            'shell' => 'clinic',
            'module' => 'clinic',
            'active' => 'clinic.dashboard',
            'clinic_capability' => ClinicAccess::CAP_VIEW_APPOINTMENTS,
            'hint' => 'مواعيد ومرضى',
        ],
        'clinic.appointments' => [
            'route' => 'clinic.appointments.index',
            'label' => 'الحجوزات',
            'info_field' => 'clinic.nav_appointments',
            'shell' => 'clinic',
            'module' => 'clinic',
            'active' => 'clinic.appointments.*',
            'clinic_capability' => ClinicAccess::CAP_VIEW_APPOINTMENTS,
        ],
        'clinic.patients' => [
            'route' => 'clinic.patients.index',
            'label' => 'المرضى',
            'niche_label' => 'entities.customer',
            'info_field' => 'clinic.nav_patients',
            'shell' => 'clinic',
            'module' => 'clinic',
            'active' => 'clinic.patients.*',
            'clinic_capability' => ClinicAccess::CAP_VIEW_CLINICAL,
        ],
        'clinic.prescriptions' => [
            'route' => 'clinic.prescriptions.index',
            'label' => 'الروشتات',
            'info_field' => 'clinic.nav_prescriptions',
            'shell' => 'clinic',
            'module' => 'clinic',
            'active' => 'clinic.prescriptions.*',
            'clinic_capability' => ClinicAccess::CAP_VIEW_CLINICAL,
        ],
        'clinic.services' => [
            'route' => 'clinic.services.index',
            'label' => 'دليل الخدمات',
            'info_field' => 'clinic.nav_services',
            'shell' => 'clinic',
            'module' => 'clinic',
            'active' => 'clinic.services.*',
            'clinic_capability' => ClinicAccess::CAP_MANAGE_SERVICES,
        ],
        'clinic.doctor_schedules' => [
            'route' => 'clinic.doctor-schedules.index',
            'label' => 'جداول الأطباء',
            'info_field' => 'clinic.nav_schedules',
            'shell' => 'clinic',
            'module' => 'clinic',
            'active' => ['clinic.doctor-schedules.*', 'clinic.blocked-slots.*'],
            'clinic_capability' => ClinicAccess::CAP_MANAGE_SERVICES,
        ],
        'clinic.settings' => [
            'route' => 'clinic.settings.index',
            'label' => 'الهوية البصرية',
            'info_field' => 'clinic.nav_settings',
            'shell' => 'clinic',
            'module' => 'clinic',
            'active' => 'clinic.settings.*',
            'admin_only' => true,
        ],

        // —— Nursery ——
        'nursery.dashboard' => [
            'route' => 'nursery.dashboard',
            'label' => 'لوحة التحكم',
            'info_field' => 'nursery.nav_dashboard',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.dashboard',
            'nursery_capability' => NurseryAccess::CAP_VIEW_DAILY,
            'hint' => 'حضور اليوم والأطفال',
        ],
        'nursery.attendance' => [
            'route' => 'nursery.attendance.index',
            'label' => 'حضور وانصراف',
            'info_field' => 'nursery.nav_attendance',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.attendance.*',
            'nursery_capability' => NurseryAccess::CAP_VIEW_DAILY,
        ],
        'nursery.children' => [
            'route' => 'nursery.children.index',
            'label' => 'الأطفال',
            'niche_label' => 'entities.child',
            'info_field' => 'nursery.nav_children',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.children.*',
            'nursery_capability' => NurseryAccess::CAP_VIEW_DAILY,
        ],
        'nursery.guardians' => [
            'route' => 'nursery.guardians.index',
            'label' => 'أولياء الأمور',
            'info_field' => 'nursery.nav_guardians',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.guardians.*',
            'feature' => 'nursery_portal',
            'nursery_capability' => NurseryAccess::CAP_VIEW_DAILY,
        ],
        'nursery.staff' => [
            'route' => 'nursery.staff.index',
            'label' => 'طاقم العمل',
            'info_field' => 'nursery.nav_staff',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.staff.*',
            'nursery_capability' => NurseryAccess::CAP_VIEW_STAFF,
        ],
        'nursery.classrooms' => [
            'route' => 'nursery.classrooms.index',
            'label' => 'الفصول',
            'niche_label' => 'entities.classroom',
            'info_field' => 'nursery.nav_classrooms',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.classrooms.*',
            'nursery_capability' => NurseryAccess::CAP_VIEW_DAILY,
        ],
        'nursery.units' => [
            'route' => 'nursery.units.index',
            'label' => 'الوحدات',
            'info_field' => 'nursery.nav_units',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.units.*',
            'nursery_capability' => NurseryAccess::CAP_VIEW_UNITS,
        ],
        'nursery.calendar' => [
            'route' => 'nursery.calendar.index',
            'label' => 'التقويم',
            'info_field' => 'nursery.nav_calendar',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.calendar.*',
            'nursery_capability' => NurseryAccess::CAP_VIEW_CALENDAR,
        ],
        'nursery.subscriptions' => [
            'route' => 'nursery.subscriptions.index',
            'label' => 'الاشتراكات',
            'info_field' => 'nursery.nav_subscriptions',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.subscriptions.*',
            'nursery_capability' => NurseryAccess::CAP_VIEW_SUBSCRIPTIONS,
        ],
        // —— مالية الحضانة (نفس مسارات Finance ERP — تسمية Nursery منفصلة) ——
        'nursery.finance' => [
            'route' => 'nursery.finance.index',
            'label' => 'ملخص المالية',
            'niche_label' => 'finance.summary',
            'info_field' => 'nursery.nav_finance',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.finance.index',
            'nursery_capability' => NurseryAccess::CAP_VIEW_FINANCE,
            'hint' => 'تحصيلات ومستحقات وصافي',
        ],
        'nursery.finance.dashboard' => [
            'route' => 'finance.dashboard',
            'label' => 'لوحة المالية',
            'niche_label' => 'finance.dashboard',
            'info_field' => 'nursery.nav_finance_dashboard',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.dashboard',
            'nursery_capability' => NurseryAccess::CAP_VIEW_FINANCE_REPORTS,
        ],
        'nursery.finance.accounts' => [
            'route' => 'finance.accounts.index',
            'label' => 'دليل الحسابات',
            'niche_label' => 'finance.accounts',
            'info_field' => 'nursery.nav_finance_accounts',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.accounts.*',
            'nursery_capability' => NurseryAccess::CAP_MANAGE_FINANCE_LEDGER,
        ],
        'nursery.finance.journals' => [
            'route' => 'finance.journals.index',
            'label' => 'القيود اليومية',
            'niche_label' => 'finance.journals',
            'info_field' => 'nursery.nav_finance_journals',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.journals.*',
            'nursery_capability' => NurseryAccess::CAP_MANAGE_FINANCE_LEDGER,
        ],
        'nursery.finance.receipts' => [
            'route' => 'finance.receipts.index',
            'label' => 'سندات التحصيل',
            'niche_label' => 'finance.receipt',
            'info_field' => 'nursery.nav_finance_receipts',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.receipts.*',
            'nursery_capability' => NurseryAccess::CAP_MANAGE_FINANCE_TREASURY,
        ],
        'nursery.finance.payments' => [
            'route' => 'finance.payments.index',
            'label' => 'سندات الصرف',
            'niche_label' => 'finance.payment',
            'info_field' => 'nursery.nav_finance_payments',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.payments.*',
            'nursery_capability' => NurseryAccess::CAP_MANAGE_FINANCE_TREASURY,
        ],
        'nursery.finance.expenses' => [
            'route' => 'finance.expenses.index',
            'label' => 'المصروفات',
            'niche_label' => 'finance.expense',
            'info_field' => 'nursery.nav_finance_expenses',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => [
                'finance.expenses.index',
                'finance.expenses.create',
                'finance.expenses.show',
                'finance.expenses.edit',
                'finance.expenses.print',
                'finance.expenses.pdf',
            ],
            'nursery_capability' => NurseryAccess::CAP_MANAGE_FINANCE_EXPENSES,
        ],
        'nursery.finance.expense_categories' => [
            'route' => 'finance.expenses.categories.index',
            'label' => 'تصنيفات المصروفات',
            'niche_label' => 'finance.expense_categories',
            'info_field' => 'nursery.nav_finance_expense_categories',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.expenses.categories.*',
            'nursery_capability' => NurseryAccess::CAP_MANAGE_FINANCE_EXPENSES,
        ],
        'nursery.finance.bank_accounts' => [
            'route' => 'finance.bank-accounts.index',
            'label' => 'البنوك',
            'niche_label' => 'finance.bank_accounts',
            'info_field' => 'nursery.nav_finance_banks',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.bank-accounts.*',
            'nursery_capability' => NurseryAccess::CAP_MANAGE_FINANCE_TREASURY,
        ],
        'nursery.finance.bank_reconciliations' => [
            'route' => 'finance.bank-reconciliations.index',
            'label' => 'التسوية البنكية',
            'niche_label' => 'finance.bank_reconciliation',
            'info_field' => 'nursery.nav_finance_bank_recon',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.bank-reconciliations.*',
            'nursery_capability' => NurseryAccess::CAP_FINANCE_ADMIN,
        ],
        'nursery.finance.ledger' => [
            'route' => 'finance.ledger.index',
            'label' => 'دفتر الأستاذ',
            'niche_label' => 'finance.ledger',
            'info_field' => 'nursery.nav_finance_ledger',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.ledger.*',
            'nursery_capability' => NurseryAccess::CAP_MANAGE_FINANCE_LEDGER,
        ],
        'nursery.finance.trial_balance' => [
            'route' => 'finance.reports.trial-balance',
            'label' => 'ميزان المراجعة',
            'niche_label' => 'finance.trial_balance',
            'info_field' => 'nursery.nav_finance_trial_balance',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.reports.trial-balance',
            'nursery_capability' => NurseryAccess::CAP_VIEW_FINANCE_REPORTS,
        ],
        'nursery.finance.profit_loss' => [
            'route' => 'finance.reports.profit-loss',
            'label' => 'الأرباح والخسائر',
            'niche_label' => 'finance.profit_loss',
            'info_field' => 'nursery.nav_finance_profit_loss',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.reports.profit-loss',
            'nursery_capability' => NurseryAccess::CAP_VIEW_FINANCE_REPORTS,
        ],
        'nursery.finance.tax_report' => [
            'route' => 'reports.tax.index',
            'label' => 'تقرير الضريبة',
            'niche_label' => 'finance.tax_report',
            'info_field' => 'nursery.nav_finance_tax_report',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'reports.tax.*',
            'nursery_capability' => NurseryAccess::CAP_VIEW_FINANCE_REPORTS,
        ],
        'nursery.finance.tax_rates' => [
            'route' => 'finance.tax-rates.index',
            'label' => 'معدلات الضريبة',
            'niche_label' => 'finance.tax_rates',
            'info_field' => 'nursery.nav_finance_tax_rates',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.tax-rates.*',
            'nursery_capability' => NurseryAccess::CAP_FINANCE_ADMIN,
        ],
        'nursery.finance.payment_method_accounts' => [
            'route' => 'finance.payment-method-accounts.edit',
            'label' => 'ربط طرق الدفع',
            'niche_label' => 'finance.payment_method_accounts',
            'info_field' => 'nursery.nav_finance_pma',
            'shell' => 'nursery',
            'module' => 'finance',
            'active' => 'finance.payment-method-accounts.*',
            'nursery_capability' => NurseryAccess::CAP_FINANCE_ADMIN,
        ],
        'nursery.settings' => [
            'route' => 'nursery.settings.index',
            'label' => 'الإعدادات',
            'info_field' => 'nursery.nav_settings',
            'shell' => 'nursery',
            'module' => 'nursery',
            'active' => 'nursery.settings.*',
            'nursery_capability' => NurseryAccess::CAP_MANAGE_SETTINGS,
        ],

        // —— Primary shells (لوحات الدخول) ——
        'crm.dashboard' => [
            'route' => 'crm.dashboard',
            'label' => 'لوحة CRM',
            'shell' => 'crm',
            'module' => 'crm',
            'active' => 'crm.dashboard',
            'hint' => 'عملاء وفرص',
        ],
        'manufacturing.dashboard' => [
            'route' => 'manufacturing.dashboard',
            'label' => 'لوحة التصنيع',
            'shell' => 'manufacturing',
            'module' => 'manufacturing',
            'active' => 'manufacturing.dashboard',
            'hint' => 'أوامر تشغيل وBOM',
        ],
        'inventory.dashboard' => [
            'route' => 'inventory.dashboard',
            'label' => 'لوحة المخزون',
            'shell' => 'inventory',
            'module' => 'inventory',
            'active' => 'inventory.dashboard',
            'hint' => 'مخازن',
        ],
        'sales.dashboard' => [
            'route' => 'sales.dashboard',
            'label' => 'لوحة المبيعات',
            'shell' => 'sales',
            'module' => 'sales',
            'active' => 'sales.dashboard',
            'hint' => 'فواتير وتحصيلات',
        ],
        'purchases.dashboard' => [
            'route' => 'purchases.dashboard',
            'label' => 'لوحة المشتريات',
            'shell' => 'purchases',
            'module' => 'purchases',
            'active' => 'purchases.dashboard',
        ],
        'hr.dashboard' => [
            'route' => 'hr.dashboard',
            'label' => 'لوحة الموارد البشرية',
            'shell' => 'hr',
            'module' => 'hr',
            'active' => 'hr.dashboard',
            'hint' => 'موظفون وحضور',
        ],

        // —— System ——
        'system.audit' => [
            'route' => 'system.audit.index',
            'label' => 'سجل التدقيق',
            'shell' => 'system',
            'active' => 'system.audit.*',
            'hint' => 'مراقبة التغييرات',
        ],
    ],

    'surfaces' => [
        'pos.full' => [
            'pos.dashboard',
            'pos.products',
            'pos.store_settings',
            'pos.cashier',
            'pos.devices',
            'pos.sessions',
            'pos.orders',
            'pos.receipts',
        ],
        'pos.store' => [
            'pos.orders',
            'pos.store_settings',
        ],
        'fleet.ops' => [
            'fleet.dashboard',
            'fleet.collections',
            'fleet.custody',
            'fleet.store_orders',
            'fleet.routes',
            'fleet.agents',
            'fleet.customers',
            'fleet.products',
        ],
        'finance.lite' => [
            'finance.dashboard',
            'finance.reports.profit_loss',
            'finance.expenses',
        ],
        'system.core' => [
            'system.audit',
        ],
        'clinic.ops' => [
            'clinic.dashboard',
            'clinic.appointments',
            'clinic.patients',
            'clinic.prescriptions',
            'clinic.services',
            'clinic.doctor_schedules',
            'clinic.settings',
        ],
        'nursery.ops' => [
            'nursery.dashboard',
            'nursery.attendance',
            'nursery.children',
            'nursery.guardians',
            'nursery.staff',
            'nursery.classrooms',
            'nursery.units',
            'nursery.calendar',
            'nursery.subscriptions',
            'nursery.settings',
        ],
        'nursery.finance.ops' => [
            'nursery.finance',
            'nursery.finance.dashboard',
            'nursery.finance.expenses',
            'nursery.finance.expense_categories',
            'nursery.finance.receipts',
            'nursery.finance.payments',
            'nursery.finance.bank_accounts',
            'nursery.finance.bank_reconciliations',
            'nursery.finance.accounts',
            'nursery.finance.journals',
            'nursery.finance.ledger',
            'nursery.finance.trial_balance',
            'nursery.finance.profit_loss',
            'nursery.finance.tax_report',
            'nursery.finance.tax_rates',
            'nursery.finance.payment_method_accounts',
        ],
        'crm.ops' => [
            'crm.dashboard',
        ],
        'manufacturing.ops' => [
            'manufacturing.dashboard',
        ],
    ],

    'profiles' => [
        'fleet_agents' => [
            'primary_shell' => 'fleet',
            'surfaces' => ['fleet.ops', 'pos.store', 'finance.lite', 'system.core'],
            'quick_link_keys' => [
                'fleet.dashboard',
                'pos.orders',
                'finance.reports.profit_loss',
            ],
        ],
        'retail' => [
            'primary_shell' => 'pos',
            'surfaces' => [
                'pos.full',
                'sales.full',
                'inventory.full',
                'purchases.full',
                'crm.ops',
                'finance.lite',
                'system.core',
            ],
            'quick_link_keys' => [
                'pos.dashboard',
                'crm.dashboard',
                'finance.reports.profit_loss',
            ],
        ],
        'manufacturing' => [
            'primary_shell' => 'manufacturing',
            'surfaces' => [
                'manufacturing.full',
                'inventory.full',
                'purchases.full',
                'sales.lite',
                'hr.lite',
                'pos.store',
                'finance.lite',
                'system.core',
            ],
            'quick_link_keys' => [
                'manufacturing.dashboard',
                'finance.reports.profit_loss',
            ],
        ],
        'medical_clinics' => [
            'primary_shell' => 'clinic',
            'surfaces' => ['clinic.ops', 'pos.store', 'finance.lite', 'system.core'],
            'quick_link_keys' => [
                'clinic.dashboard',
                'finance.reports.profit_loss',
            ],
        ],
        'nurseries' => [
            'primary_shell' => 'nursery',
            'surfaces' => ['nursery.ops', 'nursery.finance.ops', 'system.core'],
            'quick_link_keys' => [
                'nursery.dashboard',
                'nursery.finance',
            ],
        ],
        'restaurants' => [
            // shell المطعم المخصص (restaurant.ops) يُضاف في المرحلة التالية — حالياً POS هو الواجهة الأساسية.
            'primary_shell' => 'pos',
            'surfaces' => ['pos.full', 'inventory.lite', 'finance.lite', 'system.core'],
            'quick_link_keys' => [
                'pos.dashboard',
                'finance.reports.profit_loss',
            ],
        ],
        'full_erp' => [
            'primary_shell' => 'erp',
            'surfaces' => ['*'],
            'expand_all_modules' => true,
            'quick_link_keys' => [
                'pos.dashboard',
                'finance.dashboard',
            ],
        ],
    ],

    'launchers' => [
        'finance' => [
            'module' => 'finance',
            'route' => 'finance.dashboard',
            'subtitle' => 'لوحة المحاسبة',
            'iconBg' => 'rgba(2, 119, 189, 0.2)',
            'iconColor' => '#0277bd',
            'icon' => '<path d="M4 10.781c.148 1.667 1.513 2.85 3.591 3.003V15h1.043v-1.216c2.27-.179 3.678-1.438 3.678-3.3 0-1.59-.947-2.51-2.956-3.028l-.722-.187V3.467c1.122.11 1.879.714 2.07 1.616h1.471c-.166-1.6-1.54-2.748-3.54-2.875V1H7.591v1.233c-1.939.23-3.27 1.472-3.27 3.156 0 1.454.966 2.483 2.661 2.917l.61.162v4.031c-1.149-.17-1.94-.8-2.131-1.718H4z"/>',
        ],
        'inventory' => [
            'module' => 'inventory',
            'route' => 'inventory.dashboard',
            'subtitle' => 'لوحة المخزون',
            'iconBg' => 'rgba(245, 158, 11, 0.25)',
            'iconColor' => '#ea580c',
            'icon' => '<path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113z"/><path d="M15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6z"/>',
        ],
        'sales' => [
            'module' => 'sales',
            'route' => 'sales.dashboard',
            'subtitle' => 'لوحة المبيعات',
            'iconBg' => 'rgba(46, 125, 50, 0.2)',
            'iconColor' => '#2e7d32',
            'icon' => '<path d="M4 11H2v3h2v-3zm5-4H7v7h2V7zm5-5v12h-2V2h2zm-2-1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1h-2z"/>',
        ],
        'pos' => [
            'module' => 'pos',
            'route' => 'pos.dashboard',
            'subtitle' => 'لوحة نقاط البيع',
            'iconBg' => 'rgba(220, 38, 38, 0.15)',
            'iconColor' => '#dc2626',
            'icon' => '<path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm2-1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2z"/><path d="M4 3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V3zm0 4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7z"/>',
        ],
        'purchases' => [
            'module' => 'purchases',
            'route' => 'purchases.dashboard',
            'subtitle' => 'لوحة المشتريات',
            'iconBg' => 'rgba(124, 58, 237, 0.2)',
            'iconColor' => '#7c3aed',
            'icon' => '<path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5z"/>',
        ],
        'manufacturing' => [
            'module' => 'manufacturing',
            'route' => 'manufacturing.dashboard',
            'subtitle' => 'لوحة التحكم',
            'iconBg' => 'rgba(59, 130, 246, 0.18)',
            'iconColor' => '#1d4ed8',
            'icon' => '<path d="M8 1a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V1zm1 0v14h6V1H9zM2 3a1 1 0 0 1 1-1h3v14H3a1 1 0 0 1-1-1V3z"/>',
        ],
        'hr' => [
            'module' => 'hr',
            'route' => 'hr.dashboard',
            'subtitle' => 'لوحة الموارد البشرية',
            'iconBg' => 'rgba(13, 148, 136, 0.18)',
            'iconColor' => '#0d9488',
            'icon' => '<path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/><path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>',
        ],
        'clinic' => [
            'module' => 'clinic',
            'route' => 'clinic.dashboard',
            'subtitle' => 'لوحة العيادة',
            'iconBg' => 'rgba(13, 148, 136, 0.2)',
            'iconColor' => '#0d9488',
            'icon' => '<path d="M8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5z"/><path d="M6.5 0A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>',
        ],
        'crm' => [
            'module' => 'crm',
            'route' => 'crm.dashboard',
            'subtitle' => 'لوحة CRM',
            'iconBg' => 'rgba(99, 102, 241, 0.18)',
            'iconColor' => '#4f46e5',
            'icon' => '<path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>',
        ],
        'nursery' => [
            'module' => 'nursery',
            'route' => 'nursery.dashboard',
            'subtitle' => 'لوحة الحضانة',
            'iconBg' => 'rgba(251, 146, 60, 0.2)',
            'iconColor' => '#ea580c',
            'icon' => '<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/><path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492z"/>',
        ],
        'fleet' => [
            'module' => 'fleet',
            'route' => 'fleet.dashboard',
            'subtitle' => 'لوحة المناديب',
            'requires_fleet_operations' => true,
            'iconBg' => 'rgba(124, 58, 237, 0.2)',
            'iconColor' => '#7c3aed',
            'icon' => '<path d="M8 16a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm-1.5-2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm3 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/><path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V7h1.5A1.5 1.5 0 0 1 15 8.5v2.999l-1.5 1.5V13a1 1 0 0 1-1 1h-1v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5V14H5v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5V14H1a1 1 0 0 1-1-1v-1.001L0 10.5V8.5A1.5 1.5 0 0 1 1.5 7H3V3.5z"/>',
        ],
    ],

    'module_shells' => $erpNavigation['module_shells'] ?? [],

    /*
    |--------------------------------------------------------------------------
    | Dashboard widget quick actions (per module — ordered link keys)
    |--------------------------------------------------------------------------
    |
    | Each key must exist in links registry. Visibility uses the same filters as
    | navigation surfaces (profile + modules + capabilities + isDashboardQuickLinkVisible).
    */
    'dashboard_actions' => [
        'finance' => [
            'finance.dashboard',
            'finance.accounts',
            'finance.journals',
            'finance.expenses',
        ],
    ],

];

return array_merge($config, [
    'links' => array_merge($config['links'], $erpNavigation['links'] ?? []),
    'surfaces' => array_merge($config['surfaces'], $erpNavigation['surfaces'] ?? []),
]);
